# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # checking for syntax
      - id: check-yaml
      - id: check-toml
      # simple formatting
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      # checks for unresolved merge conflicts
      - id: check-merge-conflict
  # sort python imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  # format f strings
  - repo: https://github.com/ikamensh/flynt/
    rev: "1.0.1"
    hooks:
      - id: flynt
  # pyupgrade (migrate code to newer syntax)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  # format python code
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies:
          - docformatter[tomli]
        args: ["--in-place", "--config", "./pyproject.toml"]
  # format markdown, yaml, json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude_types: [python, markdown]
        args: ["--print-width", "100"]
  # lint python code
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        # check for dead code
        additional_dependencies:
          - flake8-eradicate
          - flake8-bugbear
          - flake8-simplify
          - flake8-builtins
          - flake8-comprehensions
          - flake8-use-fstring
          - flake8-docstrings
          - flake8-rst-docstrings
          - flake8-blind-except
          - flake8-requirements
          - flake8-deprecated
          - flake8-requirements
          - pep8-naming
          - darglint
          - flake8-warnings
          - flake8-pie
          - flake8-annotations
          - flake8-annotations-complexity
          - flake8-return
  # format and lint markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
      - id: markdownlint-fix
        args: ["--disable", "md013,md034,md033,md036"]
  # static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
